import { ArrowRight, Check, LoaderCircle, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { requestGraphPatches } from '../api/client'
import type { GraphPatch, ProjectState } from '../types'

export function AIResearchDialog({ state, nodeId, onClose, onApply }: { state: ProjectState; nodeId: string; onClose: () => void; onApply: (patches: GraphPatch[]) => void }) {
  const [mode, setMode] = useState<'refine' | 'decompose'>('decompose')
  const [instruction, setInstruction] = useState('补充这一环节最重要的直接下级，并说明每一环为什么值得研究。')
  const [patches, setPatches] = useState<GraphPatch[]>([])
  const [selected, setSelected] = useState(new Set<string>())
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const run = async () => { setBusy(true); setError(''); try { const result = await requestGraphPatches(state, nodeId, mode, instruction); setPatches(result); setSelected(new Set(result.map(item => item.id))); if (!result.length) setError('模型没有返回可用补丁') } catch (reason) { setError(reason instanceof Error ? reason.message : 'AI 请求失败') } finally { setBusy(false) } }
  const toggle = (id: string) => setSelected(current => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next })
  return <div className="formal-modal"><section className="ai-research-dialog"><header><div><span>AI PATCH REVIEW</span><h2>AI 产业研究 · {state.nodes[nodeId].title}</h2><p>模型只提交补丁，勾选接纳后才修改正式图谱。</p></div><button onClick={onClose}><X size={17} /></button></header>{!patches.length ? <div className="ai-request-body"><div className="ai-mode-tabs"><button className={mode === 'decompose' ? 'active' : ''} onClick={() => setMode('decompose')}>继续拆解</button><button className={mode === 'refine' ? 'active' : ''} onClick={() => setMode('refine')}>完善内容</button></div><label><span>研究要求</span><textarea rows={6} value={instruction} onChange={event => setInstruction(event.target.value)} /></label><div className="ai-safety-note"><Sparkles size={15} /><span><strong>补丁安全模式</strong>AI 返回的新增节点、内容修改和关系会逐项审核，不会直接覆盖现有项目。</span></div>{error && <div className="inline-error">{error}</div>}<button className="run-graph-ai" onClick={() => void run()} disabled={busy}>{busy ? <LoaderCircle className="spin" size={15} /> : <Sparkles size={15} />}{busy ? 'DeepSeek 正在研究…' : '生成修改建议'}</button></div> : <><div className="patch-summary"><span>共 {patches.length} 项建议 · 已选择 {selected.size} 项</span><button onClick={() => { setPatches([]); setSelected(new Set()) }}>重新生成</button></div><div className="patch-review-list">{patches.map(patch => <label key={patch.id}><input type="checkbox" checked={selected.has(patch.id)} onChange={() => toggle(patch.id)} /><span className={`patch-kind ${patch.type}`}>{patchLabel(patch.type)}</span><div><strong>{patch.after?.title || state.nodes[patch.targetId || '']?.title || `${patch.source} → ${patch.target}`}</strong>{patch.type === 'update_node' && <div className="patch-diff"><p>{patch.before?.summary || state.nodes[patch.targetId || '']?.summary || '暂无原内容'}</p><ArrowRight size={14} /><p>{patch.after?.summary || '不修改解释'}</p></div>}{patch.type === 'add_node' && <p className="patch-content">{patch.after?.summary}<small>{patch.after?.why}</small></p>}{patch.type === 'add_edge' && <p className="patch-content">新增产业关系：{patch.source} → {patch.target}</p>}<small className="patch-reason">AI 理由：{patch.reason}</small></div></label>)}</div><footer><span>所有补丁均可单独取消选择。</span><div><button onClick={onClose}>全部放弃</button><button className="primary" disabled={!selected.size} onClick={() => onApply(patches.filter(item => selected.has(item.id)))}><Check size={13} />接纳 {selected.size} 项修改</button></div></footer></>}</section></div>
}

function patchLabel(type: GraphPatch['type']) { return ({ update_node: '修改内容', add_node: '新增节点', add_edge: '新增关系' } as const)[type] }
