import { chromium } from 'file:///C:/Users/ganziyi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'

const browser = await chromium.launch({ headless: true, executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
const errors = []
let uploaded = false
let ocrRequested = false
let projectVersion = 1
let projectState = null
let simulateConflict = false
let conflictRaised = false
const members = [
  { id: 'user-owner', email: 'owner@example.com', display_name: '正式版负责人', role: 'owner' },
  { id: 'user-editor', email: 'editor@example.com', display_name: '协作研究员', role: 'editor' },
]
page.on('pageerror', error => errors.push(error.message))
await page.addInitScript(() => {
  localStorage.removeItem('industry-atlas-formal-workspace-v1')
  localStorage.removeItem('industry-atlas-workspace-v1')
  localStorage.removeItem('industry-atlas-formal-snapshots-v1')
  localStorage.setItem('industry-atlas-cloud-config-v1', JSON.stringify({ baseUrl: 'http://127.0.0.1:8000' }))
  sessionStorage.setItem('industry-atlas-cloud-token-session', 'test-token')
  sessionStorage.setItem('industry-atlas-cloud-workspace-session', JSON.stringify({ id: 'ws1', name: '正式版测试空间', role: 'owner', user: { id: 'user-owner', email: 'owner@example.com', display_name: '正式版负责人' } }))
})
await page.route(/\/api\/projects(?:\/project-formal)?$/, async route => {
  const method = route.request().method()
  if (method === 'GET') return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: 'project-formal', title: projectState?.projectTitle || 'AI算力产业链', state: projectState, version: projectVersion, updated_at: new Date().toISOString() }) })
  const payload = route.request().postDataJSON()
  if (method === 'PUT' && simulateConflict && payload.expected_version && !conflictRaised) {
    conflictRaised = true; projectVersion += 1
    return route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ detail: { code: 'project_conflict', current_version: projectVersion, updated_at: new Date().toISOString() } }) })
  }
  projectState = payload.state
  if (method === 'PUT') projectVersion += 1
  return route.fulfill({ status: method === 'POST' ? 201 : 200, contentType: 'application/json', body: JSON.stringify({ id: 'project-formal', title: payload.title, state: projectState, version: projectVersion, updated_at: new Date().toISOString() }) })
})
await page.route(/\/api\/projects\?workspace_id=/, route => {
  const workspaceId = new URL(route.request().url()).searchParams.get('workspace_id')
  const items = workspaceId === 'ws1' ? [{ id: 'project-formal', workspace_id: 'ws1', title: projectState?.projectTitle || 'AI 算力产业链', version: projectVersion, created_at: new Date().toISOString(), updated_at: new Date().toISOString() }] : []
  return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(items) })
})
await page.route('**/api/workspaces', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 'ws1', name: '正式版测试空间', role: 'owner', owner_id: 'user-owner', created_at: new Date().toISOString() }, { id: 'ws-viewer', name: '受邀只读空间', role: 'viewer', owner_id: 'other-owner', created_at: new Date().toISOString() }]) }))
await page.route('**/api/health', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ status: 'ok', service: 'industry-atlas-api' }) }))
await page.route('**/api/auth/dev-login', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ token: 'new-test-token', workspace_id: 'ws2', user: { id: 'user2', display_name: '正式版研究员' } }) }))
await page.route('**/api/auth/login', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ token: 'account-token', user: { id: 'user-owner', email: 'owner@example.com', display_name: '正式版负责人' }, workspace: { id: 'ws1', name: '正式版测试空间', role: 'owner' } }) }))
await page.route('**/api/workspaces/ws1/members', async route => {
  if (route.request().method() === 'GET') return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(members) })
  const payload = route.request().postDataJSON(); members.push({ id: 'user-new', email: payload.email, display_name: '新成员', role: payload.role })
  return route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify(members.at(-1)) })
})
await page.route(/\/api\/workspaces\/ws1\/members\/[^/]+$/, async route => {
  const memberId = route.request().url().split('/').at(-1)
  const member = members.find(item => item.id === memberId)
  if (route.request().method() === 'DELETE') { members.splice(members.findIndex(item => item.id === memberId), 1); return route.fulfill({ status: 204, body: '' }) }
  member.role = route.request().postDataJSON().role
  return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(member) })
})
await page.route('**/api/companies/sync', async route => { const payload = route.request().postDataJSON(); await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ created: 0, updated: payload.companies.length, skipped: 0, companies: payload.companies.map((data, index) => ({ id: `company-${index}`, data })) }) }) })
await page.route('**/api/ai/structured', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ run_id: 'ai-run-formal', model: 'deepseek-v4-flash', result: { patches: [{ id: 'patch-update-optical', type: 'update_node', targetId: 'optical', before: { summary: '完成高速电光与光电转换。' }, after: { summary: '完成高速电光转换，并向1.6T与硅光集成演进。', why: '直接影响AI集群的带宽、功耗和连接成本。' }, reason: '补充技术演进与产业价值' }, { id: 'patch-add-laser', type: 'add_node', parentId: 'optical', after: { id: 'laser', title: '激光器与光芯片', category: '光模块上游', summary: '提供光信号发射、调制与接收能力。', why: '决定速率、功耗、良率与成本。', metrics: ['速率', '良率'] }, reason: '补足光模块核心上游器件' }] } }) }))
await page.route(/\/api\/documents\?.*/, route => {
  if (route.request().method() === 'POST') { uploaded = true; return route.fulfill({ status: 202, contentType: 'application/json', body: JSON.stringify({ id: 'doc-formal', filename: '正式版示例年报.pdf', status: 'processing' }) }) }
  return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(uploaded ? [{ id: 'doc-formal', filename: '正式版示例年报.pdf', status: 'ready', page_count: 88, char_count: 180000, table_count: 2, extraction_count: 1, needs_ocr: 1, updated_at: new Date().toISOString() }] : []) })
})
await page.route(/\/api\/documents\/doc-formal$/, route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: 'doc-formal', filename: '正式版示例年报.pdf', status: 'ready', page_count: 88, char_count: 180000, table_count: 2, extraction_count: 1, needs_ocr: ocrRequested ? 0 : 1, updated_at: new Date().toISOString() }) }))
await page.route('**/api/documents/doc-formal/chunks', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 'chunk-1', page_number: 12, text: '公司重点布局高速光模块产品，并持续推进800G与1.6T产品。' }]) }))
await page.route('**/api/documents/doc-formal/ocr', route => { ocrRequested = true; return route.fulfill({ status: 202, contentType: 'application/json', body: JSON.stringify({ id: 'doc-formal', status: 'ocr_processing' }) }) })
await page.route('**/api/documents/doc-formal/tables', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify([{ id: 'table-formal', page_number: 36, table_number: 1, row_count: 3, column_count: 3, data: [['指标', '2025年', '2024年'], ['营业收入', '100亿元', '80亿元'], ['同比增长', '25%', '10%']] }]) }))
await page.route('**/api/documents/doc-formal/extractions', route => route.fulfill({ status: 202, contentType: 'application/json', body: JSON.stringify({ id: 'ext-formal', document_id: 'doc-formal', status: 'processing', result: null }) }))
await page.route('**/api/document-extractions/ext-formal', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ id: 'ext-formal', document_id: 'doc-formal', status: 'ready', result: { company: '正式版光通信公司', report_period: '2025 年度', summary: '主营高速光模块与光互连产品。', validation: { total: 2, matched: 1, unmatched: 1 }, findings: [{ id: 'finding-1', category: 'business', category_label: '主营业务', title: '高速光模块', value: '布局800G与1.6T产品', quote: '公司重点布局高速光模块产品', matched_pages: [12], citation_status: 'matched' }, { id: 'finding-2', category: 'risk', category_label: '主要风险', title: '客户风险', value: '客户集中度较高', quote: '没有匹配的模拟原文', matched_pages: [], citation_status: 'unmatched' }] } }) }))
await page.route('**/api/projects/project-formal/export?**', route => route.fulfill({ status: 200, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', body: 'mock-xlsx' }))

await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' })
await page.waitForSelector('.react-flow__node')
if (await page.locator('.react-flow__node').count() < 10) throw new Error('正式版产业节点没有完整渲染')
await page.locator('.react-flow__node').filter({ hasText: '光模块' }).click()
if (!(await page.locator('.inspector').textContent()).includes('带宽升级推动')) throw new Error('节点与研究卡片没有联动')
await page.locator('.research-field textarea').first().fill('正式版保存验证：光模块完成高速电光转换。')
await page.click('.save-inspector')
await page.waitForTimeout(400)
if (!(await page.evaluate(() => { const key = Object.keys(localStorage).find(item => item.startsWith('industry-atlas-project-v2:')); return key ? JSON.parse(localStorage.getItem(key)).nodes.optical.summary : '' })).includes('正式版保存验证')) throw new Error('正式版研究卡片没有自动保存')
await page.locator('.section-actions button').click()
await page.getByLabel('资料标题').fill('正式版人工证据')
await page.getByLabel('原文位置').fill('第 18 页')
await page.getByLabel('原文摘录').fill('这是经过研究员人工核验的原文摘录。')
await page.getByText('已人工核验').click()
await page.getByRole('button', { name: '保存证据' }).click()
if (!(await page.locator('.inspector').textContent()).includes('正式版人工证据')) throw new Error('正式版证据编辑没有保存')
await page.getByRole('button', { name: 'AI 研究' }).click()
await page.waitForSelector('.ai-research-dialog')
await page.getByRole('button', { name: '生成修改建议' }).click()
await page.waitForSelector('.patch-review-list')
if (await page.locator('.patch-review-list>label').count() !== 2) throw new Error('正式版 AI 补丁数量不正确')
if (!(await page.locator('.patch-diff').textContent()).includes('1.6T')) throw new Error('正式版 AI 修改前后差异未显示')
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-ai-patch-review.png', fullPage: true })
await page.getByRole('button', { name: /接纳 2 项修改/ }).click()
await page.waitForTimeout(400)
const aiPatchState = await page.evaluate(() => { const key = Object.keys(localStorage).find(item => item.startsWith('industry-atlas-project-v2:')); return JSON.parse(localStorage.getItem(key)) })
if (!aiPatchState.nodes.laser || !aiPatchState.nodes.optical.summary.includes('1.6T')) throw new Error('正式版 AI 补丁未写入图谱')
await page.waitForTimeout(250)
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-react-workbench.png', fullPage: true })

await page.getByRole('button', { name: '资料与年报' }).click()
await page.setInputFiles('input[type="file"]', { name: '正式版示例年报.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 mock') })
await page.waitForSelector('.document-ai')
if (!(await page.locator('.document-grid').textContent()).includes('88 页')) throw new Error('正式版 PDF 上传解析状态未回填')
await page.getByRole('button', { name: '运行 OCR' }).click()
await page.waitForFunction(() => Object.keys(window.localStorage).some(key => key.startsWith('industry-atlas-project-v2:')))
if (!ocrRequested) throw new Error('正式版没有发起 OCR 请求')
await page.getByRole('button', { name: '查看表格' }).click()
await page.waitForSelector('.table-viewer')
if (!(await page.locator('.table-viewer').textContent()).includes('100亿元')) throw new Error('正式版年报表格未渲染')
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-table-viewer.png', fullPage: true })
await page.getByRole('button', { name: '写入当前节点' }).click()
await page.click('.document-ai')
await page.waitForSelector('.extraction-review')
if (await page.locator('.formal-finding-list input:checked').count() !== 1) throw new Error('AI 审核没有默认选择原文匹配发现')
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-extraction-review.png', fullPage: true })
await page.getByRole('button', { name: '写入节点与公司档案' }).click()
await page.waitForSelector('.company-page')
if (!(await page.locator('.company-page').textContent()).includes('正式版光通信公司')) throw new Error('AI 发现没有写入正式版公司档案')

await page.getByRole('button', { name: '历史版本' }).click()
if (await page.locator('.snapshot-timeline>article').count() < 2) throw new Error('正式版自动快照未生成')
await page.getByRole('button', { name: '创建当前快照' }).click()
if (await page.locator('.snapshot-timeline>article').count() < 3) throw new Error('手动快照未生成')

await page.getByRole('button', { name: '导出' }).click()
await page.waitForSelector('.export-dialog')
await page.getByRole('button', { name: /Excel/ }).click()
const downloadPromise = page.waitForEvent('download')
await page.getByRole('button', { name: '导出 XLSX' }).click()
const download = await downloadPromise
if (!download.suggestedFilename().endsWith('.xlsx')) throw new Error('正式版精准导出文件名错误')

await page.getByRole('button', { name: '研究看板' }).click()
if (await page.locator('.metric-cards>article').count() !== 4) throw new Error('研究看板指标未渲染')
await page.getByRole('button', { name: '新建任务' }).click()
await page.getByLabel('任务标题').fill('正式版任务编辑验证')
await page.getByLabel('研究要求与完成标准').fill('补充行业数据并完成证据核验。')
await page.getByRole('button', { name: '保存任务' }).click()
if (!(await page.locator('.dashboard-panel').last().textContent()).includes('正式版任务编辑验证')) throw new Error('正式版研究任务未保存')
const taskCountBefore = await page.locator('.task-row').count()
await page.getByRole('button', { name: '按缺口生成' }).click()
if (await page.locator('.task-row').count() <= taskCountBefore) throw new Error('正式版没有按研究缺口生成任务')
await page.getByRole('button', { name: '开始任务' }).first().click()
if (await page.getByRole('button', { name: '完成任务' }).count() < 1) throw new Error('正式版任务状态无法推进')
await page.getByRole('button', { name: '云端项目' }).click()
await page.waitForSelector('.project-center')
await page.locator('.cloud-project-grid article').first().waitFor()
await page.waitForFunction(() => document.querySelectorAll('select[aria-label="当前研究空间"] option').length === 2)
const projectCenterText = await page.locator('.project-center').textContent()
if (!(await page.locator('.cloud-project-grid').textContent()).includes('AI 算力产业链')) throw new Error(`云端项目列表未显示当前项目：${projectCenterText}`)
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-cloud-project-center.png', fullPage: true })
await page.getByLabel('当前研究空间').selectOption('ws-viewer')
await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('industry-atlas-cloud-workspace-session')).id === 'ws-viewer')
if (!(await page.locator('.sync-action').textContent()).includes('只读模式')) throw new Error('viewer 没有进入只读状态')
await page.getByRole('button', { name: '产业图谱' }).click()
if (await page.locator('.save-inspector').count()) throw new Error('viewer 仍可编辑节点研究卡片')
await page.getByRole('button', { name: '云端项目' }).click()
await page.getByLabel('当前研究空间').selectOption('ws1')
await page.getByRole('button', { name: /打开项目|重新载入/ }).click()
await page.waitForSelector('.graph-workspace')
if (!(await page.evaluate(() => localStorage.getItem('industry-atlas-formal-cloud-project-id')))) throw new Error('打开云端项目后没有恢复项目绑定')
if (!(await page.evaluate(() => Object.keys(localStorage).some(key => key.startsWith('industry-atlas-project-v2:') && key.includes('user-owner%3Aws1%3Aproject-formal'))))) throw new Error('项目数据没有按账号、空间和项目分区保存')
await page.getByRole('button', { name: '团队与权限' }).click()
await page.waitForSelector('.member-list')
await page.waitForFunction(() => document.querySelectorAll('.member-list>article').length === 2)
if (await page.locator('.member-list>article').count() !== 2) throw new Error('正式版成员列表未渲染')
await page.getByLabel('成员邮箱').fill('new@example.com')
await page.getByRole('button', { name: '添加成员' }).click()
await page.getByText('new@example.com').waitFor()
if (!(await page.locator('.member-list').textContent()).includes('new@example.com')) throw new Error('正式版无法添加空间成员')
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-team-permissions.png', fullPage: true })
simulateConflict = true
await page.locator('.sync-action').click()
await page.waitForSelector('.conflict-dialog')
if (!(await page.locator('.conflict-dialog').textContent()).includes('云端已有更新')) throw new Error('正式版同步冲突未明确展示')
await page.screenshot({ path: 'C:/Users/ganziyi/.codex/visualizations/2026/08/05/019fd254-3f66-7ce2-9b24-af75258d2016/formal-sync-conflict.png', fullPage: true })
await page.getByRole('button', { name: '保留本地并覆盖' }).click()
await page.waitForSelector('.conflict-dialog', { state: 'detached' })
await page.getByRole('button', { name: '系统设置' }).click()
await page.waitForSelector('.connection-dialog')
if (!(await page.locator('.connection-banner').textContent()).includes('已连接')) throw new Error('正式版连接状态未显示')
await page.getByRole('button', { name: '退出登录' }).click()
await page.getByLabel('邮箱').fill('owner@example.com')
await page.getByLabel('密码').fill('correct horse battery')
await page.getByRole('button', { name: '登录研究空间' }).click()
await page.waitForFunction(() => sessionStorage.getItem('industry-atlas-cloud-token-session') === 'account-token')
if (!(await page.locator('.connection-banner').textContent()).includes('登录成功')) throw new Error('正式版邮箱账号登录失败')
if (errors.length) throw new Error(`页面错误：${errors.join(' | ')}`)
await browser.close()
console.log('formal web browser check passed')
